"use client";

import { motion, useMotionValue, useSpring } from "framer-motion";
import { useEffect, useRef, useState } from "react";

const phpLines = [
  { text: "$user = get_user_by('email', 'john@example.com');", delay: 0 },
  { text: "", delay: 0.8 },
  { text: "update_option(", delay: 1.2 },
  { text: "  'site_title',", delay: 1.6 },
  { text: "  'AI Managed Website'", delay: 2.0 },
  { text: ");", delay: 2.4 },
  { text: "", delay: 2.8 },
  { text: "wp_insert_post([", delay: 3.2 },
  { text: "  'post_title' => 'Generated by AI'", delay: 3.6 },
  { text: "]);", delay: 4.0 },
];

function AnimatedTerminal() {
  const [visibleLines, setVisibleLines] = useState<number[]>([]);
  const [cursor, setCursor] = useState(true);

  useEffect(() => {
    phpLines.forEach((line, i) => {
      setTimeout(() => {
        setVisibleLines((prev) => [...prev, i]);
      }, line.delay * 1000);
    });

    const cursorInterval = setInterval(() => setCursor((c) => !c), 530);
    return () => clearInterval(cursorInterval);
  }, []);

  return (
    <div className="glass-card rounded-2xl overflow-hidden font-mono text-sm">
      <div className="flex items-center gap-2 px-4 py-3 border-b border-white/5 bg-white/[0.02]">
        <div className="w-3 h-3 rounded-full bg-red-500/70" />
        <div className="w-3 h-3 rounded-full bg-yellow-500/70" />
        <div className="w-3 h-3 rounded-full bg-green-500/70" />
        <span className="ml-3 text-white/30 text-xs">vibewarrior.php</span>
      </div>
      <div className="p-5 space-y-0.5 min-h-[200px]">
        {phpLines.map((line, i) => (
          <div
            key={i}
            className={`transition-opacity duration-300 leading-6 ${
              visibleLines.includes(i) ? "opacity-100" : "opacity-0"
            }`}
          >
            {line.text === "" ? (
              <span>&nbsp;</span>
            ) : (
              <span>
                <span className="text-violet-400">{line.text.startsWith("$") ? line.text.split("=")[0] : ""}</span>
                {line.text.startsWith("$") ? (
                  <>
                    <span className="text-white/60">= </span>
                    <span className="text-blue-300">{line.text.split("= ")[1]}</span>
                  </>
                ) : line.text.startsWith("  '") ? (
                  <span className="text-green-300 pl-4">{line.text.trim()}</span>
                ) : line.text.startsWith("update_option") || line.text.startsWith("wp_insert_post") ? (
                  <span className="text-yellow-300">{line.text}</span>
                ) : (
                  <span className="text-white/70">{line.text}</span>
                )}
              </span>
            )}
          </div>
        ))}
        {visibleLines.length >= phpLines.length && (
          <div className="flex items-center gap-1 mt-1">
            <span className="text-violet-400">{">"}</span>
            <span
              className="inline-block w-2 h-4 bg-violet-400"
              style={{ opacity: cursor ? 1 : 0 }}
            />
          </div>
        )}
      </div>
    </div>
  );
}

const trustItems = [
  "Direct WordPress Access",
  "Runs Inside WordPress",
  "Database Access",
  "File System Access",
  "HTTPS Authenticated",
  "Sandbox Protection",
];

export default function HeroSection() {
  return (
    <section className="relative min-h-screen flex flex-col items-center justify-center pt-24 pb-16 px-6 overflow-hidden">
      {/* Background gradients */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-violet-600/10 rounded-full blur-3xl animate-glow-pulse" />
        <div className="absolute top-1/3 right-1/4 w-80 h-80 bg-blue-600/8 rounded-full blur-3xl animate-glow-pulse" style={{ animationDelay: "1.5s" }} />
        <div className="absolute bottom-1/4 left-1/2 w-64 h-64 bg-violet-500/6 rounded-full blur-3xl animate-glow-pulse" style={{ animationDelay: "3s" }} />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto w-full grid lg:grid-cols-2 gap-16 items-center">
        {/* Left */}
        <div>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-violet-500/30 bg-violet-500/10 text-violet-300 text-xs font-medium mb-8"
          >
            <span className="w-1.5 h-1.5 rounded-full bg-violet-400 animate-pulse" />
            Open Source WordPress AI Plugin
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.2 }}
            className="text-5xl md:text-6xl lg:text-7xl font-bold leading-[1.05] tracking-tight mb-6"
          >
            Your AI Can{" "}
            <span className="gradient-text">Control WordPress</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.35 }}
            className="text-lg text-white/50 leading-relaxed mb-10 max-w-xl"
          >
            VibeWarrior runs PHP inside your WordPress process. Your AI gets
            direct access to WordPress functions, the database, and the
            filesystem—without restrictive APIs.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.45 }}
            className="flex flex-wrap gap-3 mb-12"
          >
            <a
              href="https://github.com/Rankwisy/Vibeworriors/archive/refs/heads/master.zip"
              download="vibewarrior-plugin.zip"
              className="px-6 py-3 rounded-xl bg-white text-black font-semibold text-sm hover:bg-white/90 transition-all hover:scale-105 active:scale-95 flex items-center gap-2"
            >
              <svg viewBox="0 0 24 24" className="w-4 h-4 fill-black" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 16l-5-5h3V4h4v7h3l-5 5zm-7 2h14v2H5v-2z"/>
              </svg>
              Download Plugin
            </a>
            <a
              href="https://github.com/Rankwisy/vibepress"
              target="_blank"
              rel="noopener noreferrer"
              className="px-6 py-3 rounded-xl glass-card text-white font-medium text-sm hover:bg-white/5 transition-all flex items-center gap-2 border border-white/10"
            >
              <svg viewBox="0 0 24 24" className="w-4 h-4 fill-white">
                <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
              </svg>
              View GitHub
            </a>
          </motion.div>

          {/* Trust banner */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            className="flex flex-wrap gap-x-5 gap-y-2"
          >
            {trustItems.map((item, i) => (
              <motion.span
                key={item}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.7 + i * 0.07 }}
                className="flex items-center gap-1.5 text-xs text-white/40"
              >
                <span className="text-violet-400">✓</span>
                {item}
              </motion.span>
            ))}
          </motion.div>
        </div>

        {/* Right — Terminal */}
        <motion.div
          initial={{ opacity: 0, x: 40 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.8, delay: 0.3 }}
          className="animate-float"
        >
          <AnimatedTerminal />
        </motion.div>
      </div>
    </section>
  );
}
